 spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc.lob.non_contextual_creation: true

  thymeleaf:
    cache: false

  main:
    allow-bean-definition-overriding: true